site_name: api
site_description: Authentication API for GNDX Challenge
repo_url: https://github.com/abulnes16/auth-app-api
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/abulnes16">abulnes16</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
